apiVersion: v1
kind: Namespace
metadata:
  name: weave-gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-ops-frontend
  namespace: weave-gitops
  labels:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: git-ops-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
      app.kubernetes.io/component: git-ops-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weave-gitops
        app.kubernetes.io/component: git-ops-frontend
    spec:
      containers:
      - name: weave-gitops
        #image: paulofrazao/weaveworks-gitops:0.1
        image: paulofrazao/launchpad:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: git-ops-frontend
  namespace: weave-gitops
  labels:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: git-ops-frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the git-ops-frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: git-ops-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: weave-gitops
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - weave-gitops.suse.studio
    secretName: weave-gitops-suse-studio-crt
  rules:
  - host: weave-gitops.suse.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: git-ops-frontend
            port:
              number: 80
